### ISSUE TITLE
[Bug] Manhattan Project not appearing in build menu

### ISSUE THREAD

**Issue by theTyrfing** [Wahazar/augmented2#2]
Freeciv version: 2.6
Augmented version: 2.6.10
Bug Repeatability: Unknown

Hello Wahazar,

This wonder is not showing up as buildable during my game even with uranium as a local tile I am working on. The docs only indicate that this is the only requirement other than 4500 culture points and Nuclear Fission research. I am able to build it when I remove/comment out the following line in buildings ruleset for the wonder:

"Resource", "Uranium", "Local"

If there is any other information I should provide let me know.

Regards....

**Comment by Wahazar** [comment]
Thanks for testing, indeed, there should be:
"Resource", "Uranium", "City"

**Comment by theTyrfing** [comment]
Thank you. I will go test it out. Also, I think I had problem with your GBU units back in 2.6.8. However, I will open separate issue once I test with fresh copy of your 2.6.10 build to see if still present here.

**Comment by Wahazar** [comment]
Uranium bug fixed in 2.6.11 release
