### ISSUE TITLE
Ruleset error and warnings

### ISSUE THREAD

**Issue by cazfi** [Wahazar/augmented2#3]
Running the server with --warnings results in a bunch of warnings and one error (error is there even without the -w parameter). These look like what is meant to be rules are getting ignored because of wrong way of stating them in the ruleset.

> rulesetdir augmented2
2: Loading rulesets.
2: /home/cazfi/.freeciv/2.6/augmented2/terrain.ruleset: unused entry: extraui.ui_name_base_waterlock
2: /home/cazfi/.freeciv/2.6/augmented2/units.ruleset: unused entry: unit_autonomous_war_mech.tech_req,1
2: /home/cazfi/.freeciv/2.6/augmented2/units.ruleset: unused entry: unit_antimatter_fighter.tech_req,1
2: /home/cazfi/.freeciv/2.6/augmented2/units.ruleset: unused entry: unit_antimatter_bomber.tech_req,1
2: /home/cazfi/.freeciv/2.6/augmented2/units.ruleset: unused entry: unit_railgun_destroyer.tech_req,1
2: /home/cazfi/.freeciv/2.6/augmented2/units.ruleset: unused entry: unit_nuclear.tech_req,1
2: /home/cazfi/.freeciv/2.6/augmented2/buildings.ruleset: unused entry: building_cement_plant.nreqs0.type
2: /home/cazfi/.freeciv/2.6/augmented2/buildings.ruleset: unused entry: building_cement_plant.nreqs0.name
2: /home/cazfi/.freeciv/2.6/augmented2/buildings.ruleset: unused entry: building_cement_plant.nreqs0.range
2: /home/cazfi/.freeciv/2.6/augmented2/buildings.ruleset: unused entry: building_courthouse.reqs1.range,1
2: /home/cazfi/.freeciv/2.6/augmented2/buildings.ruleset: unused entry: building_steel_mill.nreqs0.type
2: /home/cazfi/.freeciv/2.6/augmented2/buildings.ruleset: unused entry: building_steel_mill.nreqs0.name
2: /home/cazfi/.freeciv/2.6/augmented2/buildings.ruleset: unused entry: building_steel_mill.nreqs0.range
2: /home/cazfi/.freeciv/2.6/augmented2/buildings.ruleset: unused entry: building_atlantic_telegraph_company.obsolete_by
1: "/home/cazfi/.freeciv/2.6/augmented2/effects.ruleset": invalid boolean value for quiet for 'effect_corruption_legalism.reqs0'.

**Comment by Wahazar** [comment]
Fixed in 2.6.14
