### ISSUE TITLE
Can't change AIs to 'hard'

### ISSUE THREAD

**Issue by chippo1** [Wahazar/augmented2#6]
I'm using 2.6.2+ (d6c60cc9cc) and `chippo: 'metamessage AUGMENTED2.6.lt ruleset, modpack installer http://149.156.194.203/~mczapkie/fc/augmented/augmented2.modpack discord:Wahazar#3898'` version of augmented2.

When trying to change the AIs to hard, I get this error message:
/hard: You are not allowed to use this command.

See attached screenshot.
![augmented2-hard](https://user-images.githubusercontent.com/50263600/75662934-a1497c00-5c78-11ea-9874-ab4ccfb8460c.png)

**Comment by chippo1** [comment]
Actually, I can't change any options at all, including changing the nation set to Extended. Everything give the error:
`You are not allowed to use this command.`

**Comment by Wahazar** [comment]
It is multiplayer server?

**Comment by chippo1** [comment]
Nope, just a normal local one. Below is the Chat transcript for the following actions:
- I start a new server and connect with the qt client
- change the ruleset to civ2civ3
- change the AIs to 'hard'
- change the ruleset to augmented2
- try to change the AIs to 'normal'

It seems that once I change the ruleset to augmented2, thereafter I can't change anything, including the ruleset.

`This is Qt-client for Freeciv.
Freeciv is free software and you are welcome to distribute copies of it under certain conditions;
See the "Copying" item on the Help menu.
Now ... Go give 'em hell!
Welcome to the Freeciv version 2.6.2+ (d6c60cc9cc) Server running at chippo-Aspire-V3-731 port 5555.
You are logged in as 'chippo' connected to Chippo.
Established control over the server. You have command access level 'hack'.
chippo: 'read civ2civ3.serv'
chippo: 'rulesetdir civ2civ3'
AI*1 has been added as Easy level AI-controlled player (classic).
/rulesetdir: Ruleset directory set to "civ2civ3"
/read: ------------------------------------------------------------------------------
/read: All options with non-default values
/read: ------------------------------------------------------------------------------
/read: In the column '##' the status of the option is shown:
/read: - a '!' means the option is locked by the ruleset.
/read: - a '+' means you may change the option.
/read: - a '~' means that option follows default value.
/read: - a '=' means the value is same as default.
/read: ------------------------------------------------------------------------------
/read: Option ## value (min, max)
/read: ------------------------------------------------------------------------------
/read: aifill + 6 (0, 150)
/read: citymindist + 3 (1, 11)
/read: flatpoles + 0 (0, 100)
/read: foggedborders + enabled
/read: generator + "Pseudo-fractal height" (FRACTAL)
/read: mapsize + "Tiles per player" (PLAYER)
/read: occupychance + 100 (0, 100)
/read: onsetbarbs + 120 (0, 32767)
/read: razechance + 10 (0, 100)
/read: restrictinfra + enabled
/read: revolentype + "Random, max always quicker" (RANDQUICK)
/read: startunits + "cwsx"
/read: techlevel + 1 (0, 100)
/read: techlossforgiveness + 0 (-1, 200)
/read: temperature + 60 (0, 100)
/read: tinyisles + enabled
/read: topology + "Wrap East-West", "Wrap North-South", and
/read: "Isometric" (WRAPX|WRAPY|ISO)
/read: unreachableprotects + disabled
/read: ------------------------------------------------------------------------------
/read: You are playing Freeciv with civ2civ3 rules:
/read: 
/read: Gameplay more similar to civ3, keeping the combat system from civ2.
/read: 
/read: Adapted for single player, with AI less aggressive at start, but more
/read: challenging at the end.
/read: 
/read: The differences from the classic ruleset are listed in full in
/read: README.civ2civ3.
/read: ------------------------------------------------------------------------------
chippo: 'Hard '
/hard: Player 'AI*2' now has AI skill level 'Hard'.
/hard: Player 'AI*3' now has AI skill level 'Hard'.
/hard: Player 'AI*4' now has AI skill level 'Hard'.
/hard: Player 'AI*5' now has AI skill level 'Hard'.
/hard: Player 'AI*1' now has AI skill level 'Hard'.
/hard: Default AI skill level set to 'Hard'.
chippo: 'read augmented2.serv'
chippo: 'rulesetdir augmented2'
AI*6 has been added as Hard level AI-controlled player (classic).
AI*7 has been added as Hard level AI-controlled player (classic).
AI*8 has been added as Hard level AI-controlled player (classic).
AI*9 has been added as Hard level AI-controlled player (classic).
AI*10 has been added as Hard level AI-controlled player (classic).
AI*11 has been added as Hard level AI-controlled player (classic).
/rulesetdir: Ruleset directory set to "augmented2"
chippo: 'set techlevel=0'
Console: 'techlevel' has been set to 0.
chippo: 'set aifill=12'
Console: 'aifill' has been set to 12.
chippo: 'cmdlevel info'
/cmdlevel: Command access level set to 'info' for connection chippo.
/cmdlevel: Command access level set to 'info' for new players.
/cmdlevel: Command access level set to 'info' for first player to grab it.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/(unknown): Unknown command '/'. Try '/help'.
/set: You are not allowed to use this command.
/(unknown): Unknown command '/'. Try '/help'.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/(unknown): Unknown command '/'. Try '/help'.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/set: You are not allowed to use this command.
/metamessage: You are not allowed to use this command.
/cmdlevel: You are not allowed to use this command.
/read: ------------------------------------------------------------------------------
/read: All options with non-default values
/read: ------------------------------------------------------------------------------
/read: In the column '##' the status of the option is shown:
/read: - a '!' means the option is locked by the ruleset.
/read: - a '+' means you may change the option.
/read: - a '~' means that option follows default value.
/read: - a '=' means the value is same as default.
/read: ------------------------------------------------------------------------------
/read: Option ## value (min, max)
/read: ------------------------------------------------------------------------------
/read: aifill 12 (0, 150)
/read: dispersion 5 (0, 10)
/read: flatpoles 0 (0, 100)
/read: foggedborders enabled
/read: killunhomed 1 (0, 100)
/read: landmass 40 (15, 85)
/read: mapsize "Tiles per player" (PLAYER)
/read: occupychance 100 (0, 100)
/read: onsetbarbs 120 (0, 32767)
/read: razechance 10 (0, 100)
/read: restrictinfra enabled
/read: revolen 2 (1, 20)
/read: revolentype "Random, max always quicker" (RANDQUICK)
/read: savepalace disabled
/read: sciencebox 160 (1, 10000)
/read: specials 400 (0, 1000)
/read: startunits "cccccf"
/read: techlossforgiveness 10 (-1, 200)
/read: techlossrestore 10 (-1, 100)
/read: temperature 70 (0, 100)
/read: tilesperplayer 250 (1, 1000)
/read: topology "Wrap East-West", "Isometric", and
/read: "Hexagonal" (WRAPX|ISO|HEX)
/read: unreachableprotects disabled
/read: victories "Spacerace", "Allied victory", and
/read: "Culture victory"
/read: (SPACERACE|ALLIED|CULTURE)
/read: ------------------------------------------------------------------------------
/read: You are playing Freeciv with augmented rules:
/read: 
/read: New, better balanced technology tree.
/read: New distinctive tiers of unit classes.
/read: New buildings and wonders.
/read: New governments.
/read: 
/read: 
/read: The differences from the classic rulesets are listed in full in
/read: freeciv forum thread, freeciv augmented2 wiki or README.augmented.txt
/read: file.n
/read: Bug tracking: https://github.com/Wahazar/augmented2/issues 
/read: ------------------------------------------------------------------------------
/normal: You are not allowed to use this command.`

**Comment by chippo1** [comment]
I managed to fix it. I edited ~/.freeciv/2.6/augmented2.serv and commented out the two lines that said "cmdlevel info". Now I can change any settings for an augmented2 game.

**Comment by Wahazar** [comment]
I changed augmented.serv file, by default it is hack level, for those who want run multiplayer server, there is commented line with info level.
